---
stages:
        - latex

CV:
        stage: latex
        image: blang/latex:latest
        script:
                - pdflatex agonzale.tex
                - pdflatex margarita.tex
        artifacts:
                paths:
                        - "*.pdf"
                expire_in: 1 week
